name: lacework-iac-example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  iac-scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create environment variables file
        run: |
          echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
          echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
          echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
          echo "EXIT_FLAG=CRITICAL=1" >> env.list

      - name: Scan the repo for vulnerabilities in IaC
        run: |
          docker run --rm --env-file env.list -v "$(pwd):/app/src" lacework/codesec:stable lacework iac scan --directory /app/src
